target: txt2img
prompt: ['this is a fish']
ddim_steps: 50
sampler_name: k_euler_a
# Adding an int to toggles enables the corresponding feature.
  # 0: Create prompt matrix (separate multiple prompts using |, and get all combinations of them)
  # 1: Normalize Prompt Weights (ensure sum of weights add up to 1.0)
  # 2: Save individual images
  # 3: Save grid
  # 4: Sort samples by prompt
  # 5: Write sample info files
  # 6: jpg samples
  # 7: Fix faces using GFPGAN
  # 8: Upscale images using Real-ESRGAN
toggles: [1, 2,4,5,7]
sampler_name: k_euler_a
ddim_eta: 0.0  # legacy name, applies to all algorithms.
n_iter: 5
batch_size: 1
cfg_scale: 7.5
# Leave blank for random seed:
seed: 219741899
height: 512
width: 512
fp:
realesrgan_model_name: 'RealESRGAN_x4plus'
variant_amount: 0